from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader

def add_cover_page(pdf_canvas, logo_path):
    width, height = A4

    # Gradient background (simple two-tone simulation)
    pdf_canvas.setFillColor(colors.HexColor("#1B3C7A"))
    pdf_canvas.rect(0, 0, width, height, fill=True, stroke=False)

    # Logo at center
    try:
        logo = ImageReader(logo_path)
        pdf_canvas.drawImage(logo, width / 2 - 1.5 * inch, height / 2, width=3 * inch, preserveAspectRatio=True)
    except Exception:
        pdf_canvas.setFillColor(colors.white)
        pdf_canvas.setFont("Helvetica-Bold", 24)
        pdf_canvas.drawCentredString(width / 2, height / 2, "PrivateVault.ai")

    # Title text
    pdf_canvas.setFillColor(colors.white)
    pdf_canvas.setFont("Helvetica-Bold", 22)
    pdf_canvas.drawCentredString(width / 2, height / 2 - 1.2 * inch, "TechDebt Executive Report")

    pdf_canvas.setFont("Helvetica", 12)
    pdf_canvas.drawCentredString(width / 2, height / 2 - 1.6 * inch, "Encrypted AI Engineering Insight Report")

    # Footer watermark
    pdf_canvas.setFont("Helvetica-Oblique", 10)
    pdf_canvas.drawCentredString(width / 2, 0.5 * inch, "Confidential — Generated by PrivateVault.ai")

def generate_techdebt_pdf(report_data, logo_path="logo.png", output_path="techdebt_report.pdf"):
    # Create a temporary cover
    cover_path = "cover_temp.pdf"
    cover = canvas.Canvas(cover_path, pagesize=A4)
    add_cover_page(cover, logo_path)
    cover.showPage()
    cover.save()

    # Now main report
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    story = []

    story.append(Paragraph("<b>Repository:</b> " + report_data["repo"], styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>AI Summary</b>", styles["Heading2"]))
    story.append(Paragraph(report_data["ai_summary"], styles["BodyText"]))
    story.append(Spacer(1, 12))

    data = [
        ["Metric", "Value"],
        ["Maintainability Index", report_data["maintainability"]],
        ["Complexity Score", report_data["complexity"]],
        ["Pylint Rating", report_data["pylint"]],
        ["Todos Remaining", report_data["todos"]],
    ]
    table = Table(data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1B3C7A")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
        ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),
    ]))
    story.append(table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("<b>AI Recommendations</b>", styles["Heading2"]))
    story.append(Paragraph(report_data["recommendations"], styles["BodyText"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph("<b>Estimated Business Impact</b>", styles["Heading2"]))
    story.append(Paragraph(f"Estimated monthly cost: ${report_data['impact']}", styles["BodyText"]))

    doc.build(story)
    print(f"✅ PDF generated at {output_path}")

report_data = {
    "repo": "github.com/example/repo",
    "ai_summary": "Your codebase shows strong structure but moderate maintainability challenges.",
    "maintainability": 82.5,
    "complexity": 7.3,
    "pylint": 8.4,
    "todos": 5,
    "recommendations": "Refactor long functions, add docstrings, and upgrade dependencies.",
    "impact": 4200
}

generate_techdebt_pdf(report_data)
